name: checkpm_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0
  fl_chart: ^0.12.2
  flutter_material_pickers: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: any
  firebase_messaging: 5.1.5


flutter:
  uses-material-design: true
  assets:
    - assets/
