name: checkpm_v2
description: A new Flutter application.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  animated_text_kit: any
  page_transition: any
  http: any
  fl_chart: any
  scrolling_page_indicator: any
  circle_chart: ^0.0.3
  heatmap_calendar: ^1.2.8
  flutter_material_pickers: 1.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf